### ISSUE TITLE
Коментар до 2 завдання

### ISSUE THREAD

**Issue by akhsunna** [Nasya/RentSkiingGear#1]
Логічної моделі можна було не надсилати. Але оскільки надіслали, то є такі зауваження:
- немає з'єднання між сутностями **Item** і **Booking**
- **Review** має зв'язок тільки з **User**, як я розумію це автор відгуку. Але до чого саме лишається відгук не зрозуміло.

---------------------------

Чомусь два варіанти фізичної моделі, на яку з них дивитись?
Розглянемо кращу з них - першу, де вже з'явився зв'язок між **Item** і **Booking**. Це добре :)
Але з **Review** все ще не добре.

----------------------------

Стосовно відгуків. Відгук можна лишати як певній речі (item), так і іншому користувачеві (user). 
Наприклад: 

відгук користувачеві
> цей чувак класний, з ним було приємно мати справу

або відгук до певної речі

> ці лижі дуже погані

В самому проекті я вже побачила, що ви додали до **Review**` belongs_to :item`. Тобто відгук можна залишати певному товару, але як щодо користувача?
Для цього ще раз уважно перечитайте цей розділ: http://guides.rubyonrails.org/association_basics.html

> With polymorphic associations, a model can belong to more than one other model, on a single association." 

Це саме те, що нам потрібно, правда ж?

----------------------------

Стосовно асоціації в моделі **Item**: `has_one :booking`. Чому has_one? 
Користувач може забронювати якусь річ на один термін, а інший користувач на інший термін пізніше, це вже буде багато бронювань (як ви і намалювали в вашій схемі).

---------------------------

Отже, вам треба додати поліморфний зв'язок для відгуків і зробити щоб моделі в проекті і схема бази даних відповідали один одному.

**Comment by Nasya** [comment]
Декілька раз перегляда моделі, переробляла їх сьогодні. Пропустила звязок в логічній моделі.

Два варіанти, бо не знала як краще буде виглядати) Другий варіант фізичної видалю.

Розділ перечитаю і перероблю Review.

Щодо `has_one :booking`:  `has_many: bookings` буде правильно. Не звернула увагу на те, що ж можна те саме, але на іншу дату орендувати.

Дякую!

**Comment by akhsunna** [comment]
@Nasya 

Добре, що використали concern. 

Але
Тепер у відгука не вистачає автора. До того ж асоціації з моделі ви забрали, а відповідні поля з бази даних не видалили.
Ще це поправте і тоді можна до наступного приступати.

**Comment by Nasya** [comment]
Я завтра зранку поправлю, ок?

Супер, дякую)

**Comment by Nasya** [comment]
Готово)

**Comment by akhsunna** [comment]
Привіт!

Тепер у моделі *User* по суті дві асоціації з однаковою назвою *reviews*
Яким чином це буде працювати?

-------------------------------------

В міграції краще було використати `remove_belongs_to` або `remove_reference`

**Comment by akhsunna** [comment]
До речі, якщо виконання завдань займає дуже мало часу, то той запас, який залишився краще присвячувати тестуванню, перевірте в консолі чи все добре працює, а ще краще спробуйте писати тести - [rspec gem](https://github.com/rspec/rspec-rails)
Бо бути впевненим в робочості коду, коли він неробочий - це зле.
Тести вас будуть підстраховувати.

**Comment by Nasya** [comment]
Перегляну сьогодні.

Щодо тестів, то там є трохи на перевірку асоціацій.

**Comment by akhsunna** [comment]
Ой, бачу. Але похвалити в даному випадку не можу.

Пряме питання: 
ми маємо об'єкт класу **User** -- `user`
в одному випадку нам треба повернути відгуки, які *він залишив* і в іншому -- відгуки, які *йому залишили*
як це можна буде зробити? адже асоціації нічим не відрізняються (`user.reviews`)

**Comment by Nasya** [comment]
Щодо міграції: робити rollback і робити нову міграцію чи це на майбутнє?

Щодо **User**: 
ось тест, який показує принцип роботи:

```
  context 'create review to user and item' do
    it 'shows reviews from one user to another and some item' do
      kate = User.create(name: 'Kate', email: 'asd@gmail.com',
                                     phone: '123123', address: 'Lviv')
      marie = User.create(name: 'Marie', email: 'ad@gmail.com',
                                       phone: '234321', address: 'Kyiv')
      snowboard = marie.items.create(name: 'Snowboard')
      rw1 = kate.reviews.create(reviewable: marie, rw_text: 'Nice')
      rw2 = kate.reviews.create(reviewable: snowboard, rw_text: 'Best board')
      rw3 = marie.reviews.create(reviewable: kate, rw_text: 'Nice communication')
      expect(kate.reviews).to eq([rw1, rw2])
      expect(marie.reviews).to eq([rw3])
    end
  end
```
Це правильно відтворена реалізація? І чи нормальний тест?

**Comment by akhsunna** [comment]
На майбутнє

-------

Ви тут перевіряєте тільки діставання авторських відгуків, а треба ще отриманих
Ну ви ж можете зробити `snowboard.reviews` -- це будуть відгуки, які були залишені цьому сноуборду, так? 
`expect(snowboard.reviews).to eq([rw2])`
І треба аналогічну перевірку, але замість сноуборда -- людину (отримувача)


Іншими словами
маємо таке в concern:
https://github.com/Nasya/RentSkiingGear/blob/b93348582ba50cf534fa90f8eb799721b7857875/RentSG-api/app/models/concerns/reviewable.rb#L7
цей concern включається в модель, яка в собі ще має таке:
https://github.com/Nasya/RentSkiingGear/blob/b93348582ba50cf534fa90f8eb799721b7857875/RentSG-api/app/models/user.rb#L6

Concern ж для чого? Для того, щоб повертались отримані відгуки
Але оскільки асоціація в моделі для авторських відгуків має таку ж назву, то вона перевизначається ту, що в concern
Зрозуміли в чому проблема?


По суті зв'язок на схемці (https://github.com/Nasya/RentSkiingGear/blob/master/DBPics/physical.png) мав би дублюватися між Users і Review

**Comment by Nasya** [comment]
Проблему я розумію, тільки не знаю як це виправити. Буду шукати.

**Comment by akhsunna** [comment]
Думаю ось так спрацює:

`has_many :authored_reviews, foreign_key: :user_id, class_name: 'Review', dependent: :destroy`

**Comment by Nasya** [comment]
`expect(snowboard.reviews).to eq([rw2])`
`expect(kate.reviews).to eq([rw3])`

не проходять перевірки

**Comment by Nasya** [comment]
`has_many :authored_reviews, foreign_key: :user_id, class_name: 'Review', dependent: :destroy`
після цього взагалі review не створює
До
![2018-03-13 13-04-22](https://user-images.githubusercontent.com/8141921/37338112-1dc6513c-26bf-11e8-88d4-e46a32a72e06.png)

Після
![2018-03-13 13-03-27](https://user-images.githubusercontent.com/8141921/37338111-1d9f841c-26bf-11e8-9de6-5d95e0a7616f.png)

**Comment by akhsunna** [comment]
думаю вам потрібно почитати детально про has_many (і інші)
http://guides.rubyonrails.org/association_basics.html#has-many-association-reference
бо код, який я написала зробив би щоб авторські відгуки діставались `user.authored_reviews`, а отримані  `user.reviews`

ну і звичайно той код тесту, який ви написали не проходить в такому випадку, адже `reviews`  в тому контексті, що ви використовуєте в тесті вже не використовується, зараз для цього є `authored_reviews`, а `user.reviews` --- це отримані користувачем, а не написані користувачем

**Comment by Nasya** [comment]
`user.authored_reviews`
не проходить, можливо я щось пропустила.

Закомітити це? Щоб можна було переглянути.

Перечитаю, дякую.

**Comment by akhsunna** [comment]
Так, давайте

**Comment by Nasya** [comment]
Є.

**Comment by akhsunna** [comment]
Ось приклад альтернативних тестів, які можна було б написати до вашого коду:
```
  context 'when create new review' do
    let(:author) { User.create(name: 'Kate') }
    let(:user) { User.create(name: 'Marie') }
    let(:item) { user.items.create(name: 'Snowboard') }
    
    it 'shows it in the received reviews list for item' do
      item_review = author.authored_reviews.create(reviewable: item, rw_text: 'Best board')
      expect(item.reviews).to eq([item_review])
      expect(item_review).to be_persisted
    end

    it 'shows it in the received reviews list for user' do
      user_review = author.authored_reviews.create(reviewable: user, rw_text: 'Nice')
      expect(user.reviews).to eq([user_review])
      expect(user_review).to be_persisted
    end

    it 'shows it in the authored reviews list' do
      review = author.authored_reviews.create(reviewable: user, rw_text: 'Best board')
      expect(author.authored_reviews).to eq([review])
      expect(review).to be_persisted
    end
  end
```

А ось ваш тест виправлений:

```
  context 'create review to user and item' do
    it 'shows reviews from one user to another and some item' do
      kate = User.create(name: 'Kate', email: 'asd@gmail.com',
                         phone: '123123', address: 'Lviv')
      marie = User.create(name: 'Marie', email: 'ad@gmail.com',
                          phone: '234321', address: 'Kyiv')
      snowboard = marie.items.create(name: 'Snowboard')
      rw1 = kate.authored_reviews.create(reviewable: marie, rw_text: 'Nice')
      rw2 = kate.authored_reviews.create(reviewable: snowboard, rw_text: 'Best board')
      rw3 = marie.authored_reviews.create(reviewable: kate, rw_text: 'Nice communication')
      expect(kate.authored_reviews).to eq([rw1, rw2])
      expect(kate.reviews).to eq([rw3])
    end
  end
```

**Comment by akhsunna** [comment]
Дуже потрібно, щоб ви зрозуміли що було не так і як працює поточна версія.

А далі можна приступати до третього

**Comment by Nasya** [comment]
Дуже гарний тест, буду вчитись так писати, а не все в купі. 
Можна закомічу як приклад?

По суті, я використовувала reviews не в тому контексті. 
Здається розумію, що і як.

**Comment by akhsunna** [comment]
Звичайно))

**Comment by Nasya** [comment]
Дякую))

Зробила модель **City** і тести до неї.
Я рухаю в правильному напрямку?
Чи зробила я 1-2 завдання?

**Comment by akhsunna** [comment]
Давайте я для цього відкрию іншу issue
